# Generated by Django 4.2.5 on 2023-09-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=25, unique=True)),
                ('EmailId', models.CharField(max_length=120, unique=True)),
                ('BirthDate', models.DateField()),
                ('Password', models.CharField(max_length=50)),
                ('PhoneNo', models.IntegerField(unique=True)),
            ],
        ),
    ]
