<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-09-30 17:30
=======
# Generated by Django 4.2.5 on 2023-09-21 10:06
>>>>>>> c865fdb7930e14e2c5d596bf02cb9abb96e0e293

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
import phone_field.models
=======
>>>>>>> c865fdb7930e14e2c5d596bf02cb9abb96e0e293


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Username', models.CharField(max_length=30, unique=True)),
                ('Email', models.EmailField(max_length=120, unique=True)),
<<<<<<< HEAD
                ('BirthDate', models.DateField()),
                ('PhoneNumber', phone_field.models.PhoneField(blank=True, max_length=31)),
=======
                ('DateOfBirth', models.DateField()),
>>>>>>> c865fdb7930e14e2c5d596bf02cb9abb96e0e293
                ('Users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
