# Generated by Django 4.2.5 on 2023-09-26 11:35

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='PhoneNo',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
