# Generated by Django 4.2.5 on 2023-09-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdetail_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Not Specified')], default=2),
            preserve_default=False,
        ),
    ]
