# Generated by Django 4.2.5 on 2023-09-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdetail_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='DateOfBirth',
            new_name='BirthDate',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='Username',
        ),
    ]
