# Generated by Django 4.2.5 on 2023-09-28 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_rename_dateofbirth_userdetail_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Not Specified')])),
                ('BirthDate', models.DateField()),
                ('PhoneNumber', phone_field.models.PhoneField(blank=True, max_length=15)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
