# Generated by Django 4.2.5 on 2023-09-28 11:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_delete_userdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='User',
            new_name='Users',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Username',
            field=models.CharField(default=None, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Email',
            field=models.EmailField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='FirstName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='LastName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='PhoneNumber',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
