# Generated by Django 4.2.5 on 2023-09-19 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTypeMaster',
            fields=[
                ('BudgetMaster', models.IntegerField(primary_key=True, serialize=False)),
                ('BudgetType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategories',
            fields=[
                ('ExpenseCatId', models.BigAutoField(primary_key=True, serialize=False)),
                ('ExpenseType', models.CharField(max_length=25)),
                ('CreatedAt', models.DateTimeField()),
                ('UpdatedAt', models.DateTimeField()),
                ('DeletedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategories',
            fields=[
                ('IncomeCatId', models.BigAutoField(primary_key=True, serialize=False)),
                ('IncomeType', models.CharField(max_length=25)),
                ('CreatedAt', models.DateTimeField()),
                ('UpdatedAt', models.DateTimeField()),
                ('DeletedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField(unique=True)),
                ('IncomeDate', models.DateTimeField()),
                ('IncomeImage', models.ImageField(upload_to='income_pics')),
                ('CreatedAt', models.DateTimeField()),
                ('UpdatedAt', models.DateTimeField()),
                ('DeletedAt', models.DateTimeField()),
                ('IncomeCatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.incomecategories')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('Expense_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField(unique=True)),
                ('ExpenseDate', models.DateTimeField()),
                ('ExpenseImage', models.ImageField(upload_to='expense_pics')),
                ('CreatedAt', models.DateTimeField()),
                ('UpdatedAt', models.DateTimeField()),
                ('DeletedAt', models.DateTimeField()),
                ('ExpenseCatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.expensecategories')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('Budget_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('BudgetAmount', models.IntegerField()),
                ('CreatedAt', models.DateTimeField()),
                ('UpdatedAt', models.DateTimeField()),
                ('DeletedAt', models.DateTimeField()),
                ('BudgetMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.budgettypemaster')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
