# Generated by Django 4.2.5 on 2023-09-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='BudgetAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budgettypemaster',
            name='BudgetMaster',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
