# Generated by Django 4.2.5 on 2023-09-20 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_budget_createdat_alter_budget_deletedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
        migrations.AlterField(
            model_name='budget',
            name='DeletedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
        migrations.AlterField(
            model_name='budget',
            name='UpdatedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='DeletedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='UpdatedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
        migrations.AlterField(
            model_name='expensecategories',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
        migrations.AlterField(
            model_name='expensecategories',
            name='DeletedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
        migrations.AlterField(
            model_name='expensecategories',
            name='UpdatedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
        migrations.AlterField(
            model_name='income',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
        migrations.AlterField(
            model_name='income',
            name='DeletedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
        migrations.AlterField(
            model_name='income',
            name='UpdatedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
        migrations.AlterField(
            model_name='incomecategories',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
        migrations.AlterField(
            model_name='incomecategories',
            name='DeletedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
        migrations.AlterField(
            model_name='incomecategories',
            name='UpdatedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 17, 23, 771162)),
        ),
    ]
