# Generated by Django 4.2.5 on 2023-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='ExpenseCatId',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='ExpenseCategories',
        ),
    ]
