# Generated by Django 4.2.5 on 2023-09-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_rename_user_id_expense_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='id',
            new_name='User_id',
        ),
        migrations.AlterField(
            model_name='expense',
            name='Amount',
            field=models.IntegerField(),
        ),
    ]
