# Generated by Django 4.2.5 on 2023-09-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_rename_id_expense_user_id_alter_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='Amount',
            field=models.IntegerField(),
        ),
    ]
