# Generated by Django 4.2.5 on 2023-10-25 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_expense_expensedate_alter_income_incomedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Amount',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='ExpenseDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 9, 8, 43, 539962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='Amount',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='IncomeDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 9, 8, 43, 539962, tzinfo=datetime.timezone.utc)),
        ),
    ]
