# Generated by Django 4.2.5 on 2023-10-26 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_expense_expensenote_income_expensenote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='ExpenseNote',
            new_name='IncomeNote',
        ),
        migrations.AlterField(
            model_name='expense',
            name='ExpenseDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 12, 18, 57, 532167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='IncomeDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 12, 18, 57, 532167, tzinfo=datetime.timezone.utc)),
        ),
    ]
