# Generated by Django 4.2.5 on 2023-10-31 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_expense_expensedate_alter_income_incomedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='DeletedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='ExpenseDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 11, 35, 4, 859434, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='UpdatedAt',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='DeletedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='IncomeDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 11, 35, 4, 859434, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='UpdatedAt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
