# Generated by Django 4.2.5 on 2023-11-01 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_alter_expense_expensedate_alter_income_incomedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='ExpenseDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 7, 35, 51, 34646, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='IncomeDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 7, 35, 51, 34646, tzinfo=datetime.timezone.utc)),
        ),
    ]
