# Generated by Django 4.2.5 on 2023-11-01 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_alter_expense_expensedate_alter_income_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='ExpenseDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 9, 10, 14, 161523, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='IncomeDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 9, 10, 14, 159480, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='UpdatedAt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
