# Generated by Django 4.2.5 on 2023-11-02 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_alter_expense_expensedate_alter_income_incomedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='ExpenseDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 5, 20, 8, 193689, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='IncomeDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 5, 20, 8, 180245, tzinfo=datetime.timezone.utc)),
        ),
    ]
